### PR TITLE
Consistent spacing around prefixes, and timestamps

### PR DESCRIPTION
**Pull request by matthewoates**
Two features:

1: Consistent spacing around prefixes
This makes the logs easier to parse by starting the log message at the same place for each line. Tested in node/browser  + colors/no colors.
This breaks slightly in a few cases. It formats based off of the longest prefix that Logdown has seen, so as you can see in the example the `demo` prefix is created on its own, is shorter than `foo:bar`, and therefore doesn't line up. Also, chrome adds some indentation for errors in the console, but hopefully your app isn't emitting very many errors.

screen shot 2015-10-11 at 1 44 03 pm

screen shot 2015-10-11 at 12 41 28 pm

2: Added timestamps
Would like to add support for timestamp formatting, but that would add weight to the library. For now, it's all or nothing.

screen shot 2015-10-11 at 1 35 04 pm
screen shot 2015-10-11 at 1 42 28 pm

I'd like to add log levels as well. Assuming the significance Error > Warn > Info > log > debug, you'd set your log level to any of those methods, and only see those events or more significant events. (eg: log level of Warn will only show Error and Warn)

Another note: the styles seem to be completely broken for firefox:
screen shot 2015-10-11 at 12 48 47 pm

### CODE REVIEW

**Comment by caiogondim** [comment]
About **Consistent spacing around prefixes**
I like the feature, but only under a configuration flag.
That should be optional.

About **timestamps**
I also like it, but it should come under a configuration flag.
And placement, i like more it being at the end of the line with lower contrast.

About **log levels**
It is an interesting idea and i like it very much.
Makes sense to go under a configuration as well.

About **style bug on Firefox**
It was a bug on Firefox itself and it seems to be already fixed.
Try updating Firefox and let me know if this works.

**Comment by caiogondim** [comment]
@matthewoates BTW, would you mind submitting the features on different pull request?
Makes it easier to debug, merge and (hopefully not) rollback.

But anyways, thanks for the amazing pull request and discussion.

**Comment by matthewoates** [comment]
Sure, and no problem. I'll cherry-pick the timestamps into another PR, and will add the log level features as well. May add the web worker support I mentioned ages ago as well.

**Comment by matthewoates** [comment]
Also, firefox is rendering as expected after the update.

**Comment by caiogondim** [comment]
Closing this PR.
Waiting for the separate ones.

**Pull request closed without merging**
