### PR TITLE
Added logAllErrors option

### PR DESCRIPTION
**Pull request by bahmutov**
Most of the time in production I want to disable all normal logs, but still log `foo.error` calls. This pull request adds an option when creating a new logger to log error messages, even if the logger is disabled. I also added a static method to log all errors for all loggers already existing.

### CODE REVIEW

**Comment by caiogondim** [comment]
@bahmutov Thanks again for the amazing PR.

Even though i see a use case on what you are relating, i don't want to overcomplicate the API.
`.disable()` should silence, and if we add this flag, the behavior will not be that simple.

But is quite easy to overcome what you want.
You can just set a no-op function to `warn`, `info` and `log` like this:
```js
Logdown.prototype.log = function() {}
Logdown.prototype.warn = function() {}
Logdown.prototype.info = function() {}
```
And only `error` will be logged.

Let me know of what you think.

**Comment by caiogondim** [comment]
Maybe i should put this on README as well

**Comment by bahmutov** [comment]
Sure, I can actually get around using the methods you provided (I think) in my bahmutov/debug-logdown project

**Comment by caiogondim** [comment]
Please let me know about new feature requests and eventual bugs. Lets work together =)

**Comment by bahmutov** [comment]
You got it, man

**Pull request closed without merging**
